Traduction des nouvelles clés et mises à jour de quelques clés existantes
Fonderie-VTT/fr-core pull request #1
Opened 2024-05-18 18:29 UTC by Qaw

2024-05-18 21:08 UTC, DjLeChuck requested changes
De manière générale, les hints servent à expliquer ce qu’une option fait, pas ce que l’on doit faire. Du coup, à moins que le texte en VO n’utilise explicitement le « you », on ne devrait pas utiliser la 2è personne du pluriel.

2024-05-18 21:08 UTC, DjLeChuck commented on fr.json
> +    "TOKEN.HEXAGONAL_SHAPE_TRAPEZOID_1": "Trapezoid (Variante 1)",
`Trapèze`

2024-05-18 21:08 UTC, DjLeChuck commented on fr.json
> +    "TOKEN.HEXAGONAL_SHAPE_TRAPEZOID_2": "Trapezoid (Variante 2)",
`Trapèze`

2024-05-18 21:08 UTC, DjLeChuck commented on fr.json
> +            "hint": "Spécifiez explicitement un chemin pour l'illustration placée sur l'anneau dynamique de token. Si non fourni, le sujet de l'anneau est le même que la texture standard du token."
`Indique explicitement` (même raison que plus haut, cela me semble plus correct comme verbe dans ce contexte)

2024-05-18 21:08 UTC, DjLeChuck commented on fr.json
> +    "TYPES.RegionBehavior.executeMacro": "Exécuter la macro",
`une macro`

2024-05-18 21:08 UTC, DjLeChuck commented on fr.json
> +    "TYPES.RegionBehavior.executeScript": "Exécuter le script",
`un script`

2024-05-18 21:13 UTC, Qaw commented on fr.json
> +    "ADVENTURE.ImportOverwriteTitle": "Ecraser le contenu existant ?",
Je suis d'accord, j'ai déjà modifier des réécrire en écraser ... mais pas globalement.

2024-05-18 21:24 UTC, Qaw commented
> De manière générale, les hints servent à expliquer ce qu’une option fait, pas ce que l’on doit faire. Du coup, à moins que le texte en VO n’utilise explicitement le « you », on ne devrait pas utiliser la 2è personne du pluriel.
> 
> Une fois le fichier terminé, je serais d’avis de faire une passe globale pour changer toutes les simple quotes en `’` et toutes les doubles quotes en `« »` si ça ne dérange personne.

Complétement d'accord sur la 2ième personne, j'en ai changé en les voyant, mais pas de recherche systématique.

2024-05-18 22:00 UTC, Qaw commented on fr.json
> +    "CONTROLS.RegionSnap": "Lorsqu'il est actif, toute forme que vous dessinez sur une région avec l'un des outils de forme sera alignée sur la grille.",
Si actif

2024-05-18 22:10 UTC, Qaw commented on fr.json
> +    "CONTROLS.DisableToolclips": "Désactivez les clips d'outils dans les paramètres",
Tu parles de quel changement ?

2024-05-18 22:14 UTC, Qaw commented on fr.json
> +    "SETTINGS.ColorSchemeDefault": "Défaut du navigateur",
Je tente

2024-05-18 22:14 UTC, DjLeChuck commented on fr.json
> +    "CONTROLS.DisableToolclips": "Désactivez les clips d'outils dans les paramètres",
`Désactiver` qui devient `Désactivez`

2024-05-19 16:37 UTC, Qaw commented on fr.json
> +    "CONTROLS.DisableToolclips": "Désactivez les clips d'outils dans les paramètres",
Pour moi c'est sous-entendu, vous pouvez désactiver les clips d'outils... ça s'affiche en bas de tout les cliptools

2024-05-19 16:41 UTC, Qaw commented on fr.json
> +    "SETTINGS.ColorSchemeDefault": "Défaut du navigateur",
Trop long je  laisse

2024-05-19 17:01 UTC, DjLeChuck commented on fr.json
> +    "CONTROLS.DisableToolclips": "Désactivez les clips d'outils dans les paramètres",
OK en effet c’est mieux. 👍🏻

2024-05-20 20:44 UTC, merged